[package]
name = "mtg_tree_classifier"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = {version = "0.12.15", default-features = false, features = ["blocking", "gzip", "rustls-tls"]}
serde_json = "1.0"
